csuf_colleges = ["Arts",
                 "Business and Economics",
                 "Communications",
                 "Education",
                 "Engineering and Computer Science",
                 "Health and Human Development",
                 "Humanities and Social Sciences",
                 "Natural Sciences and Mathematics",
                 ]

csuf_departments = {
    "Arts": [
        "Music",
        "Theatre and Dance",
        "Visual Arts"
    ],
    "Business and Economics": [
        "Business Administration",
        "Economics",
        "International Business"
    ],
    "Communications": [
        "Communications",
        "Human Communication Studies",
        "Cinema and Television Arts"
    ],
    "Education": [
        "Educational Leadership",
        "Elementary & Bilingual Education",
        "Literacy and Reading Education",
        "Secondary Education",
        "Special Education"
    ],
    "Engineering and Computer Science": [
        "Civil and Environmental Engineering",
        "Computer Engineering",
        "Computer Science",
        "Electrical Engineering",
        "Mechanical Engineering"
    ],
    "Health and Human Development": [
        "Child and Adolescent Studies",
        "Counseling",
        "Human Services",
        "Kinesiology",
        "Nursing",
        "Public Health",
        "Social Work"
    ],
    "Humanities and Social Sciences": [
        "American Studies",
        "Anthropology",
        "Comparative Literature",
        "Criminal Justice",
        "English",
        "Environmental Studies",
        "Ethnic Studies",
        "European Studies",
        "French",
        "Geography",
        "History",
        "Japanese",
        "Latin American Studies",
        "Liberal Studies",
        "Linguistics",
        "Philosophy",
        "Political Science",
        "Psychology",
        "Public Administration",
        "Sociology",
        "Spanish",
        "Women and Gender Studies"
    ],
    "Natural Sciences and Mathematics": [
        "Biological Science",
        "Chemistry & Biochemistry",
        "Geological Sciences",
        "Mathematics",
        "Physics"
    ]
}

department_to_degree_levels = {
    "Music": ["Bachelor of Arts", "Master of Arts"],
    "Theatre and Dance": ["Bachelor of Arts", "Master of Arts", "Master of Fine Arts"],
    "Visual Arts": ["Bachelor of Fine Arts", "Master of Fine Arts"],
    "Business Administration": ["Bachelor of Arts", "Master of Business Administration"],
    "Economics": ["Bachelor of Arts", "Master of Arts"],
    "International Business": ["Bachelor of Arts"],
    "Communications": ["Bachelor of Arts", "Master of Arts"],
    "Human Communication Studies": ["Bachelor of Arts"],
    "Cinema and Television Arts": ["Bachelor of Arts"],
    "Educational Leadership": ["Master of Science", "Doctor of Education"],
    "Elementary & Bilingual Education": ["Bachelor of Arts"],
    "Literacy and Reading Education": ["Bachelor of Arts", "Master of Science"],
    "Secondary Education": ["Master of Science"],
    "Special Education": ["Master of Science"],
    "Civil and Environmental Engineering": ["Bachelor of Science", "Master of Science"],
    "Computer Engineering": ["Bachelor of Science", "Master of Science"],
    "Computer Science": ["Bachelor of Science", "Master of Science"],
    "Electrical Engineering": ["Bachelor of Science", "Master of Science"],
    "Mechanical Engineering": ["Bachelor of Science", "Master of Science"],
    "Child and Adolescent Studies": ["Bachelor of Science"],
    "Counseling": ["Master of Science"],
    "Human Services": ["Bachelor of Science"],
    "Kinesiology": ["Bachelor of Science", "Master of Science"],
    "Nursing": ["Bachelor of Science", "Master of Science", "Doctor of Nursing Practice"],
    "Public Health": ["Bachelor of Science"],
    "Social Work": ["Master of Social Work"],
    "American Studies": ["Bachelor of Arts", "Master of Arts"],
    "Anthropology": ["Bachelor of Arts", "Master of Arts"],
    "Comparative Literature": ["Bachelor of Arts"],
    "Criminal Justice": ["Bachelor of Arts"],
    "English": ["Bachelor of Arts", "Master of Arts"],
    "Environmental Studies": ["Master of Science"],
    "Ethnic Studies": ["Bachelor of Arts"],
    "European Studies": ["Bachelor of Arts"],
    "French": ["Bachelor of Arts"],
    "Geography": ["Bachelor of Arts", "Master of Arts"],
    "History": ["Bachelor of Arts", "Master of Arts"],
    "Japanese": ["Bachelor of Arts"],
    "Latin American Studies": ["Bachelor of Arts"],
    "Liberal Studies": ["Bachelor of Arts"],
    "Linguistics": ["Bachelor of Arts", "Master of Arts"],
    "Philosophy": ["Bachelor of Arts"],
    "Political Science": ["Bachelor of Arts", "Master of Arts"],
    "Psychology": ["Bachelor of Arts", "Master of Arts", "Master of Science"],
    "Public Administration": ["Bachelor of Arts", "Master of Public Administration"],
    "Sociology": ["Bachelor of Arts", "Master of Arts"],
    "Spanish": ["Bachelor of Arts", "Master of Arts"],
    "Women and Gender Studies": ["Bachelor of Arts"],
    "Biological Science": ["Bachelor of Science", "Master of Science"],
    "Chemistry & Biochemistry": ["Bachelor of Science", "Master of Science"],
    "Geological Sciences": ["Bachelor of Science", "Master of Science"],
    "Mathematics": ["Bachelor of Arts", "Master of Arts"],
    "Physics": ["Bachelor of Science", "Master of Science"]
}

department_degree_to_degrees = {
    ("Music", "Bachelor of Arts"): ["Music B.A."],
    ("Theatre and Dance", "Bachelor of Arts"): ["Theatre Arts B.A."],
    ("Theatre and Dance", "Master of Arts"): ["Theatre Arts M.A."],
    ("Theatre and Dance", "Master of Fine Arts"): ["Theatre Arts: Design and Technical Production M.F.A.", "Theatre Arts: Directing M.F.A."],
    ("Visual Arts", "Bachelor of Fine Arts"): ["Visual Arts B.F.A."],
    ("Visual Arts", "Master of Fine Arts"): ["Visual Arts M.F.A."],
    ("Business Administration", "Bachelor of Arts"): ["Business Administration B.A."],
    ("Business Administration", "Master of Business Administration"): ["MBA"],
    ("Economics", "Bachelor of Arts"): ["Economics B.A."],
    ("Economics", "Master of Arts"): ["Economics M.A."],
    ("International Business", "Bachelor of Arts"): ["International Business B.A."],
    ("Communications", "Bachelor of Arts"): ["Communications B.A."],
    ("Human Communication Studies", "Bachelor of Arts"): ["Human Communication Studies B.A."],
    ("Cinema and Television Arts", "Bachelor of Arts"): ["Cinema and Television Arts B.A."],
    ("Educational Leadership", "Master of Science"): ["Educational Leadership M.S."],
    ("Educational Leadership", "Doctor of Education"): ["Educational Leadership Ed.D."],
    ("Elementary & Bilingual Education", "Bachelor of Arts"): ["Elementary & Bilingual Education B.A."],
    ("Literacy and Reading Education", "Master of Science"): ["Literacy and Reading Education M.S."],
    ("Secondary Education", "Master of Science"): ["Secondary Education M.S."],
    ("Special Education", "Master of Science"): ["Special Education M.S."],
    ("Civil and Environmental Engineering", "Bachelor of Science"): ["Civil Engineering B.S."],
    ("Civil and Environmental Engineering", "Master of Science"): ["Civil Engineering M.S."],
    ("Computer Engineering", "Bachelor of Science"): ["Computer Engineering B.S."],
    ("Computer Engineering", "Master of Science"): ["Computer Engineering M.S."],
    ("Computer Science", "Bachelor of Science"): ["Computer Science B.S."],
    ("Computer Science", "Master of Science"): ["Computer Science M.S."],
    ("Electrical Engineering", "Bachelor of Science"): ["Electrical Engineering B.S."],
    ("Electrical Engineering", "Master of Science"): ["Electrical Engineering M.S."],
    ("Mechanical Engineering", "Bachelor of Science"): ["Mechanical Engineering B.S."],
    ("Mechanical Engineering", "Master of Science"): ["Mechanical Engineering M.S."],
    ("Child and Adolescent Studies", "Bachelor of Science"): ["Child and Adolescent Development B.S."],
    ("Counseling", "Master of Science"): ["Counseling M.S."],
    ("Human Services", "Bachelor of Science"): ["Human Services B.S."],
    ("Kinesiology", "Bachelor of Science"): ["Kinesiology B.S."],
    ("Kinesiology", "Master of Science"): ["Kinesiology M.S."],
    ("Nursing", "Bachelor of Science"): ["Nursing B.S."],
    ("Nursing", "Master of Science"): ["Nursing M.S."],
    ("Nursing", "Doctor of Nursing Practice"): ["Doctor of Nursing Practice D.N.P."],
    ("Public Health", "Bachelor of Science"): ["Public Health B.S."],
    ("Social Work", "Master of Social Work"): ["Social Work M.S.W."],
    ("American Studies", "Bachelor of Arts"): ["American Studies B.A."],
    ("American Studies", "Master of Arts"): ["American Studies M.A."],
    ("Anthropology", "Bachelor of Arts"): ["Anthropology B.A."],
    ("Anthropology", "Master of Arts"): ["Anthropology M.A."],
    ("Comparative Literature", "Bachelor of Arts"): ["Comparative Literature B.A."],
    ("Criminal Justice", "Bachelor of Arts"): ["Criminal Justice B.A."],
    ("English", "Bachelor of Arts"): ["English B.A."],
    ("English", "Master of Arts"): ["English M.A."],
    ("Environmental Studies", "Master of Science"): ["Environmental Studies M.S."],
    ("Ethnic Studies", "Bachelor of Arts"): ["Ethnic Studies B.A."],
    ("European Studies", "Bachelor of Arts"): ["European Studies B.A."],
    ("French", "Bachelor of Arts"): ["French B.A."],
    ("Geography", "Bachelor of Arts"): ["Geography B.A."],
    ("Geography", "Master of Arts"): ["Geography M.A."],
    ("History", "Bachelor of Arts"): ["History B.A."],
    ("History", "Master of Arts"): ["History M.A."],
    ("Japanese", "Bachelor of Arts"): ["Japanese B.A."],
    ("Latin American Studies", "Bachelor of Arts"): ["Latin American Studies B.A."],
    ("Liberal Studies", "Bachelor of Arts"): ["Liberal Studies B.A."],
    ("Linguistics", "Bachelor of Arts"): ["Linguistics B.A."],
    ("Linguistics", "Master of Arts"): ["Linguistics M.A."],
    ("Philosophy", "Bachelor of Arts"): ["Philosophy B.A."],
    ("Political Science", "Bachelor of Arts"): ["Political Science B.A."],
    ("Political Science", "Master of Arts"): ["Political Science M.A."],
    ("Psychology", "Bachelor of Arts"): ["Psychology B.A."],
    ("Psychology", "Master of Arts"): ["Psychology M.A."],
    ("Psychology", "Master of Science"): ["Clinical Psychology M.S."],
    ("Public Administration", "Bachelor of Arts"): ["Public Administration B.A."],
    ("Public Administration", "Master of Public Administration"): ["Public Administration M.P.A."],
    ("Sociology", "Bachelor of Arts"): ["Sociology B.A."],
    ("Sociology", "Master of Arts"): ["Sociology M.A."],
    ("Spanish", "Bachelor of Arts"): ["Spanish B.A."],
    ("Spanish", "Master of Arts"): ["Spanish M.A."],
    ("Women and Gender Studies", "Bachelor of Arts"): ["Women and Gender Studies B.A."],
    ("Biological Science", "Bachelor of Science"): ["Biological Science B.S."],
    ("Biological Science", "Master of Science"): ["Biological Science M.S."],
    ("Chemistry & Biochemistry", "Bachelor of Science"): ["Chemistry B.S."],
    ("Chemistry & Biochemistry", "Master of Science"): ["Chemistry M.S."],
    ("Geological Sciences", "Bachelor of Science"): ["Geological Sciences B.S."],
    ("Geological Sciences", "Master of Science"): ["Geological Sciences M.S."],
    ("Mathematics", "Bachelor of Arts"): ["Mathematics B.A."],
    ("Mathematics", "Master of Arts"): ["Mathematics M.A."],
    ("Physics", "Bachelor of Science"): ["Physics B.S."],
    ("Physics", "Master of Science"): ["Physics M.S."]
}
